.TH "coreos" "1" ""  ""


.SH NAME
.PP
coreos utils mkMkdown \- generates Markdown documentation


.SH SYNOPSIS
.PP
\fBcoreos utils mkMkdown\fP [OPTIONS]


.SH DESCRIPTION
.PP
generates Markdown documentation


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for mkMkdown


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users

.PP
\fB\-\-json\fP[=false]
    outputs in JSON for easy 3rd party integration


.SH SEE ALSO
.PP
\fBcoreos utils(1)\fP,


.SH HISTORY
.PP
