.TH "corectld" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectld\-stop \- Stops corectld


.SH SYNOPSIS
.PP
\fBcorectld stop\fP


.SH DESCRIPTION
.PP
Stops corectld


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectld(1)\fP


.SH HISTORY
.PP
