.TH "coreos" "1" ""  ""


.SH NAME
.PP
coreos pull \- pull a CoreOS image from upstream


.SH SYNOPSIS
.PP
\fBcoreos pull\fP [OPTIONS]


.SH DESCRIPTION
.PP
pull a CoreOS image from upstream


.SH OPTIONS
.PP
\fB\-\-channel\fP="alpha"
    CoreOS channel

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for pull

.PP
\fB\-\-version\fP="latest"
    CoreOS version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users

.PP
\fB\-\-json\fP[=false]
    outputs in JSON for easy 3rd party integration


.SH SEE ALSO
.PP
\fBcoreos(1)\fP,


.SH HISTORY
.PP
