.TH "corectld" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectld\-start \- Starts corectld


.SH SYNOPSIS
.PP
\fBcorectld start\fP


.SH DESCRIPTION
.PP
Starts corectld


.SH OPTIONS
.PP
\fB\-D\fP, \fB\-\-domain\fP="coreos.local"
    sets the dns domain under which the created VMs will operate

.PP
\fB\-r\fP, \fB\-\-recursive\-nameservers\fP=[8.8.8.8:53,8.8.4.4:53]
    coma separated list of the recursive nameservers to be used by the embedded dns server

.PP
\fB\-u\fP, \fB\-\-user\fP=""
    sets the user that will 'own' the corectld instance


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectld(1)\fP


.SH HISTORY
.PP
