.TH "corectld" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectld \- CoreOS over macOS made simple.


.SH SYNOPSIS
.PP
\fBcorectld [flags]\fP


.SH DESCRIPTION
.PP
CoreOS over macOS made simple. 
\[la]http://github.com/genevera/corectl\[ra]
Copyright (c) 2015\-2016, António Meireles


.SH OPTIONS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for corectld


.SH SEE ALSO
.PP
\fBcorectld\-start(1)\fP, \fBcorectld\-status(1)\fP, \fBcorectld\-stop(1)\fP, \fBcorectld\-version(1)\fP


.SH HISTORY
.PP
