.TH "corectl" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectl\-query \- Display information about the running CoreOS instances


.SH SYNOPSIS
.PP
\fBcorectl query [VMids]\fP


.SH DESCRIPTION
.PP
Display information about the running CoreOS instances


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    display a table with extended information about running CoreOS instances

.PP
\fB\-i\fP, \fB\-\-ip\fP[=false]
    displays given instance IP address

.PP
\fB\-j\fP, \fB\-\-json\fP[=false]
    outputs in JSON for easy 3rd party integration

.PP
\fB\-l\fP, \fB\-\-log\fP[=false]
    displays given instance boot logs location

.PP
\fB\-o\fP, \fB\-\-online\fP[=false]
    tells if at boot time VM had connectivity to outter world

.PP
\fB\-t\fP, \fB\-\-tty\fP[=false]
    displays given instance tty's location

.PP
\fB\-u\fP, \fB\-\-up\fP[=false]
    tells if a given VM is up or not

.PP
\fB\-U\fP, \fB\-\-uuid\fP[=false]
    returns VM's UUID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
