.TH "corectld" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectld\-start \- Starts corectld


.SH SYNOPSIS
.PP
\fBcorectld start\fP


.SH DESCRIPTION
.PP
Starts corectld


.SH OPTIONS
.PP
\fB\-u\fP, \fB\-\-user\fP=""
    sets the user that will 'own' the corectld instance


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectld(1)\fP


.SH HISTORY
.PP
