.TH "corectl" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectl\-put \- copy file to inside VM


.SH SYNOPSIS
.PP
\fBcorectl put path/to/file VMid:/file/path/on/destination\fP


.SH DESCRIPTION
.PP
copy file to inside VM


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH EXAMPLE
.PP
.RS

.nf
  // copies 'filePath' into '/destinationPath' inside VMid
  corectl put filePath VMid:/destinationPath

.fi
.RE


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
