

.SH NAME
.PP
coreos utils \- some developer focused utilies


.SH SYNOPSIS
.PP
\fBcoreos utils\fP [OPTIONS]


.SH DESCRIPTION
.PP
some developer focused utilies


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for utils


.SH SEE ALSO
.PP
\fBcoreos(1)\fP, \fBcoreos\-utils\-mkMan(1)\fP, \fBcoreos\-utils\-mkMkdown(1)\fP,


.SH HISTORY
.PP
