.TH "corectl" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectl\-rm \- Remove(s) CoreOS image(s) from the local filesystem


.SH SYNOPSIS
.PP
\fBcorectl rm\fP


.SH DESCRIPTION
.PP
Remove(s) CoreOS image(s) from the local filesystem


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-channel\fP="alpha"
    CoreOS channel

.PP
\fB\-p\fP, \fB\-\-purge\fP[=false]
    purges outdated images

.PP
\fB\-v\fP, \fB\-\-version\fP="latest"
    CoreOS version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
