.TH "coreos" "1" ""  ""


.SH NAME
.PP
coreos kill \- halts a running VM


.SH SYNOPSIS
.PP
\fBcoreos kill\fP [OPTIONS]


.SH DESCRIPTION
.PP
halts a running VM


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    halts all running instances

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for kill


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-debug\fP[=false]
    adds extra verbosity, and options, for debugging purposes and/or power users

.PP
\fB\-\-json\fP[=false]
    outputs in JSON for easy 3rd party integration


.SH SEE ALSO
.PP
\fBcoreos(1)\fP,


.SH HISTORY
.PP
