.TH "corectl" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectl\-run \- Boots a new CoreOS instance


.SH SYNOPSIS
.PP
\fBcorectl run\fP


.SH DESCRIPTION
.PP
Boots a new CoreOS instance


.SH OPTIONS
.PP
\fB\-b\fP, \fB\-\-boot\fP=""
    additional arguments to the kernel boot

.PP
\fB\-c\fP, \fB\-\-channel\fP="alpha"
    CoreOS channel stream

.PP
\fB\-L\fP, \fB\-\-cloud\_config\fP=""
    cloud\-config file location (either an URL or a local path)

.PP
\fB\-N\fP, \fB\-\-cpus\fP=1
    VM number of virtual CPUs

.PP
\fB\-x\fP, \fB\-\-extra\fP=""
    additional arguments to the hypervisor

.PP
\fB\-m\fP, \fB\-\-memory\fP=1024
    VM's RAM, in MB, per instance (1024 < memory < 8192)

.PP
\fB\-n\fP, \fB\-\-name\fP=""
    names the VM (default is VM's UUID)

.PP
\fB\-o\fP, \fB\-\-offline\fP[=false]
    doesn't go online to check for newer images than the locally available ones unless there is none available.

.PP
\fB\-r\fP, \fB\-\-root\fP=""
    append a (persistent) root volume to VM

.PP
\fB\-H\fP, \fB\-\-shared\-homedir\fP[=false]
    mounts (via NFS) host's homedir inside VM

.PP
\fB\-k\fP, \fB\-\-sshkey\fP=""
    VM's default ssh key

.PP
\fB\-u\fP, \fB\-\-uuid\fP="random"
    VM's UUID

.PP
\fB\-v\fP, \fB\-\-version\fP="latest"
    CoreOS version

.PP
\fB\-p\fP, \fB\-\-volume\fP=[]
    append disk volumes to VM


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
