

.SH NAME
.PP
coreos pull \- pull a CoreOS image from upstream


.SH SYNOPSIS
.PP
\fBcoreos pull\fP [OPTIONS]


.SH DESCRIPTION
.PP
pull a CoreOS image from upstream


.SH OPTIONS
.PP
\fB\-\-channel\fP="alpha"
    CoreOS channel

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for pull

.PP
\fB\-\-version\fP="latest"
    CoreOS version


.SH SEE ALSO
.PP
\fBcoreos(1)\fP,


.SH HISTORY
.PP
