

.SH NAME
.PP
coreos ps \- lists running CoreOS instances


.SH SYNOPSIS
.PP
\fBcoreos ps\fP [OPTIONS]


.SH DESCRIPTION
.PP
lists running CoreOS instances


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP[=false]
    shows extended info about running instances

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for ps


.SH SEE ALSO
.PP
\fBcoreos(1)\fP,


.SH HISTORY
.PP
