.TH "corectl" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectl\-ssh \- Attach to or run commands inside a running CoreOS instance


.SH SYNOPSIS
.PP
\fBcorectl ssh VMid ["command1;..."]\fP


.SH DESCRIPTION
.PP
Attach to or run commands inside a running CoreOS instance


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH EXAMPLE
.PP
.RS

.nf
  corectl ssh VMid                 // logins into VMid
  corectl ssh VMid "some commands" // runs 'some commands' inside VMid and exits

.fi
.RE


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
