.TH "corectl" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectl\-ps \- Lists running CoreOS instances


.SH SYNOPSIS
.PP
\fBcorectl ps\fP


.SH DESCRIPTION
.PP
Lists running CoreOS instances


.SH OPTIONS
.PP
\fB\-j\fP, \fB\-\-json\fP[=false]
    outputs in JSON for easy 3rd party integration


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
