.TH "coreos" "1" ""  ""


.SH NAME
.PP
coreos utils mkMan \- generates man pages


.SH SYNOPSIS
.PP
\fBcoreos utils mkMan\fP [OPTIONS]


.SH DESCRIPTION
.PP
generates man pages


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for mkMan


.SH SEE ALSO
.PP
\fBcoreos utils(1)\fP,


.SH HISTORY
.PP
