.TH "corectl" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectl\-version \- Shows version information


.SH SYNOPSIS
.PP
\fBcorectl version\fP


.SH DESCRIPTION
.PP
Shows version information


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
