.TH "corectl" "1" "" " " "" 
.nh
.ad l


.SH NAME
.PP
corectl\-pull \- Pulls a CoreOS image from upstream


.SH SYNOPSIS
.PP
\fBcorectl pull\fP


.SH DESCRIPTION
.PP
Pulls a CoreOS image from upstream


.SH OPTIONS
.PP
\fB\-c\fP, \fB\-\-channel\fP="alpha"
    CoreOS channel

.PP
\fB\-f\fP, \fB\-\-force\fP[=false]
    forces the rebuild of an image, if already local

.PP
\fB\-v\fP, \fB\-\-version\fP="latest"
    CoreOS version

.PP
\fB\-w\fP, \fB\-\-warmup\fP[=false]
    ensures that all (populated) channels are on their latest versions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-d\fP, \fB\-\-debug\fP[=false]
    adds additional verbosity, and options, directed at debugging purposes and power users


.SH SEE ALSO
.PP
\fBcorectl(1)\fP


.SH HISTORY
.PP
