.TH "coreos" "1" ""  ""


.SH NAME
.PP
coreos utils mkMkdown \- generates Markdown documentation


.SH SYNOPSIS
.PP
\fBcoreos utils mkMkdown\fP [OPTIONS]


.SH DESCRIPTION
.PP
generates Markdown documentation


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for mkMkdown


.SH SEE ALSO
.PP
\fBcoreos utils(1)\fP,


.SH HISTORY
.PP
