.TH "coreos" "1" ""  ""


.SH NAME
.PP
coreos version \- displays the version number


.SH SYNOPSIS
.PP
\fBcoreos version\fP [OPTIONS]


.SH DESCRIPTION
.PP
displays the version number


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for version


.SH SEE ALSO
.PP
\fBcoreos(1)\fP,


.SH HISTORY
.PP
